### ISSUE TITLE
Sort the resources in each section in alphabetical order

### ISSUE THREAD

**Issue by phuoc-ng** [mojpm/frontend-development#4]
I can make a PR for this.

**Comment by mojpm** [comment]
Make the PR. Keep in mind that we have free and paid resources. Do not mix these. I suggest that you sort the free resources first then the paid resources. Thanks

**Comment by phuoc-ng** [comment]
Will do!

**Comment by PL2001** [comment]
[Uploading 98211276...]

**Comment by mojpm** [comment]
@PL2001 ????🤔

**Comment by gifTa4gupzawkikwaq** [comment]
> 
> [Uploading 98211276...]

**Comment by gifTa4gupzawkikwaq** [comment]
> 
> [Uploading 98211276...]

**Comment by ChinmayMhatre** [comment]
Is this issue still open would like to contribute

**Comment by mojpm** [comment]
Hey @ChinmayMhatre , Yes this issue is still open. Your contribution would be great

**Comment by ChinmayMhatre** [comment]
Ok I will make the updates and create a pr !

**Comment by ChinmayMhatre** [comment]
Do I sort the table of content  in ascending as well? or just the individual resources?

**Comment by mojpm** [comment]
Just the resources will do fine

**Comment by ChinmayMhatre** [comment]
check out the pr

**Comment by mojpm** [comment]
Hey @ChinmayMhatre Thanks for your contribution. I'll get to the pr ASAP
